### ISSUE TITLE
Vbird requires Rhino+Grasshopper

### ISSUE THREAD

**Issue by jonnor** [fellesverkstedet/fabricatable-machines#1]
Rhino+Grasshopper is primarily used because @JensDyvik is a guru deluxe in it, and has over many years developed lots of very powerful plugins and workflows in it. But we would like to get rid of needing these expensive and non-free software, so that people can use and hack on the projects without the barrier of aquiring a Rhino license.

Several aspects would have to be reproduced (more-or-less from scratch?), for fully realizing this:
- Rack&pinion geometry generator of the low-backlash, CNC-friendly roller-style-pinion (parametric CAD)
- The axis model, including plainbearings, carriage plate and connection geometry (parametric CAD)
- Toolpath generation, including the non-standard operations with the birdbeak bit (CAM)

**Comment by JensDyvik** [comment]
V-Bird has been replaced by the simpler Chamfer rail system, which is design to fabricated with genral CAM solutions. Experiments with freecad looks promising. https://github.com/fellesverkstedet/fabricatable-machines/tree/master/chamferrail
