### ISSUE TITLE
Fabacademy fork project

### ISSUE THREAD

**Issue by UltraMej** [fellesverkstedet/fabricatable-machines#15]
I,

We used your machine design in order to build a new one :)

Details on this group page and repo:
http://fab.academany.org/2018/labs/fablabdigiscope/group2018/index.html
https://gitlab.fabcloud.org/academany/fabacademy/2018/labs/fablabdigiscope/site/tree/master/group2018

Direct access to the video of it "working" on my FabAcademy page:
http://fab.academany.org/2018/labs/fablabdigiscope/students/nciri-mejdi/Assignments_15.html
http://fab.academany.org/2018/labs/fablabdigiscope/students/nciri-mejdi/Assignments_16.html

Thanks for the inspiration =)

Force et Lumière,
Mejdi.

**Comment by JensDyvik** [comment]
Awesome work!  Thank you so much for sharing. your machine has been added to the family overview here: https://github.com/fellesverkstedet/fabricatable-machines/wiki/Machine-family
