### ISSUE TITLE
Vbird missing step-by-step instructions on how to reproduce

### ISSUE THREAD

**Issue by jonnor** [fellesverkstedet/fabricatable-machines#2]
Currently we're still a bit in prototyping/R&D phase, but results have been promising. A step-by-step would help people interested in reproducing the work to be able to do so.

**Comment by JensDyvik** [comment]
Step-by-step instructions are now available for the newer generation Chamfer rail system:
https://github.com/fellesverkstedet/fabricatable-machines/tree/master/chamferrail
