### ISSUE TITLE
Porting to OpenSCAD or similar

### ISSUE THREAD

**Issue by kr15h** [fellesverkstedet/fabricatable-machines#35]
Hi! Has there been any discussion about porting this to OpenSCAD or similar open source parametric CAD system?

**Comment by hwalseng** [comment]
Hi, Krisjanis. From what i know the design has been done in Fusion 360 and Rhino so far, according to what the person designing knows and has access to. I think it would be interesting to have a go at designing a machine in FreeCad so it's open source from start to finish. I'm planning to start on this after som learning and testing more of FreeCads capabilities and limitations. If you would elaborate on your interest and motivation I could provide you with some more thoughts from my point of view. I've built a Wooden Humphrey, so far, that Jens Dyvik designed in Rhino(?).
